#!/bin/sh

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1

SETTING="${CWD}/setting.sh"

if [ -f "$SETTING" ]; then
    . "$SETTING"
else
    echo "Error: Unable to load the repository setting: $SETTING" >&2
    exit 1
fi

if [ ! -x "${BIN_DIR}/${EXECUTABLE}" ]; then
    echo "${EXECUTABLE} is not compiled" >&2
    exit 1
fi

exec "${BIN_DIR}/${EXECUTABLE}" "$@"